const siteLanguage={
    "en":{ // English
        "name": "Language: English",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Hi, [[USER]]!",
        "signUp": "Sign Up",
        "signOut": "Log Out",
        "signIn": "Log In",
        "mySys": "My [[SYSTEM]]",
        "settings": "Settings",
        "myForum": "My Forum",
        "info": "Information",
        "about": "About",
        "tutorial": "Tutorial",
        "glossary": "Glossary",
        "changelog": "Changelog",
        "crisis": "In Crisis?",
        "back": "Go Back",
        "system": "System",
        "tos": "Terms of Service",
        "pp": "Privacy Policy",
        "phil": "Philosophy",
        "comm": "Communal Journal"
    },
    "es":{ // Spanish
        "name": "Idioma: español",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Hola, [[USER]]!",
        "signUp": "Regístrate",
        "signOut": "Cerrar sesión",
        "signIn": "Iniciar sesión",
        "mySys": "Mi [[SYSTEM]]",
        "settings": "Configuración",
        "myForum": "Foro",
        "info": "Información",
        "about": "Sobre nosotros",
        "tutorial": "Guía",
        "glossary": "Glosario",
        "changelog": "Registro de cambios",
        "crisis": "Intervención en crisis",
        "back": "Volver",
        "system": "Sistema",
        "tos": "Términos de Servicio",
        "pp": "Política de Privacidad",
        "phil": "Filosofía",
        "comm": "Diario Comunitario"
    },
    "fr":{ // French
        "name": "Langue : Français",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Salut, [[USER]]!",
        "signUp": "Inscrivez-vous",
        "signOut": "Déconnectez-vous",
        "signIn": "Connectez-vous",
        "mySys": "Mon [[SYSTEM]]",
        "settings": "Paramètres",
        "myForum": "Forum",
        "info": "Informations",
        "about": "À propos de nous",
        "tutorial": "Guider",
        "glossary": "Glossaire",
        "changelog": "Journal des modifications",
        "crisis": "Intervention de crise",
        "back": "Retour",
        "system": "Système",
        "tos": "Conditions d'utilisation",
        "pp": "Politique de confidentialité",
        "phil": "Philosophie",
        "comm": "Agenda Collectif"
    },
    "de":{ // German
        "name": "Sprache: Deutsch",
        "title": "Lighthouse",
        "greeting": "Hallo, [[USER]]!",
        "signUp": "Melden Sie sich an",
        "signOut": "Melden Sie sich ab",
        "signIn": "Melden Sie sich an",
        "mySys": "Mein [[SYSTEM]]",
        "settings": "Einstellungen",
        "myForum": "Forum",
        "info": "Informationen",
        "about": "Über uns",
        "tutorial": "Leitfaden",
        "glossary": "Glossar",
        "changelog": "Änderungsprotokoll",
        "crisis": "Krisenintervention",
        "back": "Gehen Sie zurück",
        "system": "System",
        "tos": "Nutzungsbedingungen",
        "pp": "Datenschutzrichtlinie",
        "phil": "Philosophie",
        "comm": "Gemeinsames Tagebuch"
    },
    "ko":{ // Korean
        "name": "언어: 한국어",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "안녕하세요, [[USER]]님!",
        "signUp": "가입",
        "signOut": "로그아웃",
        "signIn": "로그인",
        "mySys": "내 [[SYSTEM]]",
        "settings": "설정",
        "myForum": "포럼",
        "info": "정보",
        "about": "회사 소개",
        "tutorial": "가이드",
        "glossary": "용어집",
        "changelog": "변경내역",
        "crisis": "위기 개입",
        "back": "돌아가기",
        "system": "체계",
        "tos": "서비스 약관",
        "pp": "개인정보 보호정책",
        "phil": "철학",
        "comm": "집단 일기"
    },
    "pl":{ // Polish
        "name": "Język: polski",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Witaj, [[USER]]!",
        "signUp": "Zarejestruj się",
        "signOut": "Wyloguj się",
        "signIn": "Zaloguj się",
        "mySys": "Mój [[SYSTEM]]",
        "settings": "Ustawienia",
        "myForum": "Forum",
        "info": "Informacje",
        "about": "O nas",
        "tutorial": "Przewodnik",
        "glossary": "Glosariusz",
        "changelog": "Lista zmian",
        "crisis": "Interwencja kryzysowa",
        "back": "Go Back",
        "system": "Wróć",
        "tos": "Regulamin",
        "pp": "Polityka prywatności",
        "phil": "Filozofia",
        "comm": "Dziennik wspólnotowy"
    },
    "fil":{ // Filipino
        "name": "Wika: Filipino",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Kumusta, [[USER]]!",
        "signUp": "Mag-sign Up",
        "signOut": "Mag-sign Out",
        "signIn": "Mag-sign In",
        "mySys": "Aking [[SYSTEM]]",
        "settings": "Mga Setting",
        "myForum": "Forum",
        "info": "Impormasyon",
        "about": "Tungkol sa amin",
        "tutorial": "Patnubay",
        "glossary": "Talasalitaan",
        "changelog": "Changelog",
        "crisis": "Panghihimasok sa krisis",
        "back": "Bumalik ka",
        "system": "Sistema",
        "tos": "Mga Tuntunin ng Serbisyo",
        "pp": "Patakaran sa Privacy",
        "phil": "Pilosopiya",
        "comm": "Kolektibong Talaarawan"
    },
    "jp":{ // Japanese
        "name": "言語: 日本語",
        "title": "Lighthouse", // シンプルに保つ
        "greeting": "こんにちは, [[USER]]!",
        "signUp": "サインアップ",
        "signOut": "ログアウト",
        "signIn": "ログイン",
        "mySys": "私の [[SYSTEM]]",
        "settings": "設定",
        "myForum": "私のフォーラム",
        "info": "情報",
        "about": "について",
        "tutorial": "チュートリアル",
        "glossary": "用語集",
        "changelog": "変更履歴",
        "crisis": "危機ですか?",
        "back": "戻る",
        "system": "システム",
        "tos": "利用規約",
        "pp": "プライバシーポリシー",
        "phil": "哲学",
        "comm": "コミュニティジャーナル"
    },
    "uk":{ // Ukranian
        "name": "Мова: українська",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Привіт, [[USER]]!",
        "signUp": "Зареєструватися",
        "signOut": "Вихід",
        "signIn": "Увійдіть",
        "mySys": "Моя [[SYSTEM]]",
        "settings": "Налаштування",
        "myForum": "Мій форум",
        "info": "Інформація",
        "about": "Про нас",
        "tutorial": "Як використовувати",
        "glossary": "Глосарій",
        "changelog": "Журнал змін",
        "crisis": "Кризова інтервенція",
        "back": "Попередній",
        "system": "Система",
        "tos": "Умови надання послуг",
        "pp": "Політика конфіденційності",
        "phil": "Філософія",
        "comm": "Спільний щоденник"
    },
    "gd":{ // Gaelic, Scotland
        "name": "Cànan: Scots Gaelic",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Halo, [[USER]]!",
        "signUp": "Clàradh",
        "signOut": "Clàraich a-mach",
        "signIn": "Clàraich a-steach",
        "mySys": "Mo [[SYSTEM]]",
        "settings": "Suidhichidhean",
        "myForum": "Mo fhòram",
        "info": "Fiosrachadh",
        "about": "Mu thimchioll",
        "tutorial": "Treòir",
        "glossary": "Briathrachas",
        "changelog": "Ùrachaidhean",
        "crisis": "Ann an èiginn slàinte inntinn?",
        "back": "Cùl",
        "system": "Siostam",
        "tos": "Cumhachan seirbheis",
        "pp": "Poileasaidh Dìomhaireachd",
        "phil": "Feallsanachd",
        "comm": "Leabhar-latha Coimhearsnachd"
    },
    "ie":{ // Irish
        "name": "Teanga: Gaeilge",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Dia dhaoibh, [[USER]]!",
        "signUp": "Cláraigh",
        "signOut": "Logáil Amach",
        "signIn": "Logáil isteach",
        "mySys": "Mo [[SYSTEM]]",
        "settings": "Socruithe",
        "myForum": "Mo fóram",
        "info": "Eolas",
        "about": "Fúinn",
        "tutorial": "Treoir",
        "glossary": "Stór focal",
        "changelog": "Nuashonruithe",
        "crisis": "Idirghabháil Meabhair-Shláinte",
        "back": "Cùl",
        "system": "Córas",
        "tos": "Téarmaí seirbhíse",
        "pp": "Beartas Príobháideachta",
        "phil": "Fealsúnacht",
        "comm": "Dialann Phobail"
    },
    "it":{ // Italian
        "name": "Lingua: italiano",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Ciao, [[USER]]!",
        "signUp": "Iscriviti",
        "signOut": "Esci",
        "signIn": "Accedi",
        "mySys": "Mio [[SYSTEM]]",
        "settings": "Impostazioni",
        "myForum": "Mio forum",
        "info": "Informazione",
        "about": "Chi siamo",
        "tutorial": "Tutorial",
        "glossary": "Glossario",
        "changelog": "Log delle modifiche",
        "crisis": "Intervento sulla salute mentale",
        "back": "Indietro",
        "system": "Sistema",
        "tos": "Termini di servizio",
        "pp": "Informativa sulla privacy",
        "phil": "Filosofia",
        "comm": "Diario Comunitario"
    },
    "eo":{ // Esperanto
        "name": "Lingvo: Esperanto",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "Saluton, [[USER]]!",
        "signUp": "Aliĝu",
        "signOut": "Elsaluti",
        "signIn": "Ensalutu",
        "mySys": "Mia [[SYSTEM]]",
        "settings": "Agordoj",
        "myForum": "Mia Forumo",
        "info": "Informoj",
        "about": "Pri ni",
        "tutorial": "Gvidilo",
        "glossary": "Terminaro",
        "changelog": "Ŝanĝprotokolo",
        "crisis": "Kriza interveno",
        "back": "Reiru",
        "system": "Sistemo",
        "tos": "Servokondiĉoj",
        "pp": "Privateca Politiko",
        "phil": "Filozofio",
        "comm": "Komunuma Taglibro"
    },
"ru": { // Russian
    "name": "Язык: Русский",
    "title": "Lighthouse", // Сохраняем простоту
    "greeting": "Привет, [[USER]]!",
    "signUp": "Зарегистрироваться",
    "signOut": "Выйти",
    "signIn": "Войти",
    "mySys": "Моя [[SYSTEM]]",
    "settings": "Настройки",
    "myForum": "Мой Форум",
    "info": "Информация",
    "about": "О нас",
    "tutorial": "Учебник",
    "glossary": "Глоссарий",
    "changelog": "История изменений",
    "crisis": "В кризисе?",
    "back": "Назад",
    "system": "Система",
    "tos": "Условия обслуживания",
    "pp": "Политика конфиденциальности",
    "phil": "Философия",
    "comm": "Общественный журнал"
},
    "ar":{ // Arabic
        "name": "اللغة: العربية",
        "title": "Lighthouse", // Now unused; Keeps things simple
        "greeting": "مرحباً!",
        "signUp": "إنشاء حساب",
        "signOut": "تسجيل خروج",
        "signIn": "تسجيل الدخول",
        "mySys": "[[SYSTEM]]",
        "settings": "إعدادات",
        "myForum": "المنتدى الخاص بي",
        "info": "معلومة",
        "about": "معلومات عنا",
        "tutorial": "درس تعليمي",
        "glossary": "قائمة كلمات",
        "changelog": "سجل التغيير",
        "crisis": "في أزمة الصحة العقلية؟",
        "back": "الصفحة السابقة",
        "system": "نظام",
        "tos": "شروط الخدمة",
        "pp": "سياسة الخصوصية",
        "phil": "فلسفة",
        "comm": "يوميات جماعية"
    },
    "zh": { // Chinese
    "name": "语言: 中文",
    "title": "Lighthouse", // 保持简单
    "greeting": "你好, [[USER]]!",
    "signUp": "注册",
    "signOut": "登出",
    "signIn": "登录",
    "mySys": "我的 [[SYSTEM]]",
    "settings": "设置",
    "myForum": "我的论坛",
    "info": "信息",
    "about": "关于",
    "tutorial": "教程",
    "glossary": "术语表",
    "changelog": "更新日志",
    "crisis": "遇到危机吗?",
    "back": "返回",
    "system": "系统",
    "tos": "服务条款",
    "pp": "隐私政策",
    "phil": "哲学",
    "comm": "社区日志"
}

}


exports.siteLanguage = siteLanguage;